version: "3"
services:
  server:
    build: .
    ports:
      - "${8080}:${8080}"
    environment:
      - SERVER_PORT=8080
    depends_on:
      - db
    networks:
      - db_network
    restart: always

networks:
  db_network:
    driver: bridge